#!/bin/bash

. ./muck.config
cp $MUCKOUT $MUCKOUT.bak
gzip -f $MUCKOUT.bak
cp $MUCKOUT $MUCKDB
echo -n "($MUCKNAME on port $MAINPORT from $MUCKDB): "
./protomuck $MUCKDB $MUCKOUT $MAINPORT $MOREPORTS
