#!/bin/sh

# $Header: /export/home/davin/tmp/protocvs/proto1.0/proto,v 1.1.1.1 2000-09-20 18:25:49 akari Exp $HOME/proto/proto,v 1.1 1996/09/19 03:26:44 jtraub Exp $
# $Log: not supported by cvs2svn $
#
# Revision 1.2  2000/06/27 21:45:13  moose
# Update for ProtoMUCK
#
# Revision 1.1  1996/09/19 03:26:44  jtraub
# Initial revision
#

# Start/stop the netmuck server.

HOME=$HOME

case "$1" in
start)	$HOME/proto/game/restart ;;
on)	$HOME/proto/game/restart ;;
stop)	kill `cat $HOME/proto/game/protomuck.pid` ;;
off)	kill `cat $HOME/proto/game/protomuck.pid` ;;
*)	echo "Usage: $0 start|stop"; exit 1 ;;
esac
exit 0

