#line 2 "mcplex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /export/home/davin/tmp/protocvs/protomuck/src/backup/mcplex.c,v 1.1.1.1 2000-09-18 01:04:29 akari Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
static yyconst short int yy_accept[365] =
    {   0,
        0,    0,    0,    0,   73,   71,    2,    1,   51,   70,
       71,   71,   55,   52,   60,   61,   57,   59,   66,   58,
       28,   56,    9,   63,   62,   49,   67,   50,   68,   71,
       69,   54,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   64,   53,   65,   71,   71,
        2,    1,   51,   70,   71,   71,   55,   52,   60,   61,
       57,   59,   66,   58,   28,   56,    9,   63,   62,   49,
       67,   50,   68,   71,   69,   54,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   64,
       53,   65,   71,    2,   46,    0,    7,    8,   47,   39,

       40,   28,   28,    4,    0,    9,   38,   42,   45,   43,
       44,   41,   37,   28,   28,   28,   28,   13,   28,   28,
       28,   12,   28,   28,   28,   28,   28,   28,   28,   48,
        0,    0,    0,    0,    0,    6,    0,    2,   46,    0,
        7,    8,   47,    0,   39,   40,   28,   28,    4,    0,
        9,   38,   42,   45,   43,   44,   41,   37,   28,   28,
       28,   28,   13,   28,   28,   28,   12,   28,   28,   28,
       28,   28,   28,   28,   48,    0,    0,    0,    0,    0,
        0,    3,   28,   28,   28,   28,   28,   14,   28,   28,
       28,   28,   28,   28,   19,   27,   28,    0,    0,    0,

        0,    0,    0,    0,    0,    5,    0,    3,    0,   28,
       28,   28,   28,   28,   14,   28,   28,   28,   28,   28,
       28,   19,   27,   28,    0,    0,    0,    0,    0,    0,
        0,   28,   22,   28,   28,   10,   11,   28,   28,   15,
       28,   28,   28,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   28,   22,   28,   28,   10,   11,   28,   28,
       15,   28,   28,   28,    0,    0,    0,    0,    0,    0,
        0,    0,   17,   28,   28,   28,   28,   28,   28,   24,
        0,    0,    0,    0,    0,    0,    0,    0,    3,   17,
       28,   28,   28,   28,   28,   28,   24,    0,    0,    0,

        0,    0,    0,    0,    0,   28,   28,   28,   25,   16,
       20,    0,   34,   31,    0,    0,    0,    0,   32,   28,
       28,   28,   25,   16,   20,    0,   34,    6,    0,    0,
        0,    0,   32,   28,   23,   28,   28,   30,   33,   35,
        0,    0,   28,   23,   28,   28,   30,    6,   35,    0,
        0,   18,   26,   28,   36,   29,   18,   26,   28,   36,
       29,   21,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,   28,   29,   30,   26,    1,   31,   32,   33,   34,

       35,   36,   26,   37,   38,   26,   39,   40,   26,   41,
       42,   43,   26,   44,   45,   46,   47,   48,   49,   26,
       50,   26,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    3,    1,    4,    1,
        1,    1,    1,    1,    3,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1
    } ;

static yyconst short int yy_base[370] =
    {   0,
        0,  703,   53,  702,  708,  711,  105,  711,  684,  711,
       92,    0,  711,  696,  711,  711,  711,  691,  711,  688,
      678,   97,   93,  682,  711,   91,  678,   93,  671,  674,
      711,  711,   94,   95,   97,   96,   98,   99,  106,  100,
      108,  102,  104,  103,  105,  711,  646,  711,  133,  141,
      153,  711,  147,  145,  156,  178,  150,  173,  161,  174,
      175,  176,  179,  182,  213,  261,  678,  262,  193,  263,
      264,  265,  267,  671,  228,  230,  651,  131,  165,  654,
      161,  657,  657,  644,  655,  640,  646,  656,  649,  268,
      270,  281,  320,  197,  711,  666,  665,  665,  711,  711,

      711,  657,  711,  711,  678,  215,  711,  711,  711,  711,
      711,  711,  711,  265,  247,  266,  268,  655,  270,  140,
      272,  654,  276,  273,  274,  278,  281,  277,  289,  711,
      643,  297,  201,  636,  306,  711,  328,  340,  332,  337,
      344,  658,  346,  348,  349,  357,    0,  361,  362,  363,
      656,  365,  366,  368,  369,  370,  374,  381,  639,  628,
      631,  635,    0,  625,  625,  627,    0,  618,  353,  620,
      627,  621,  619,  624,  383,  386,  387,  388,  389,    0,
      658,  711,  286,  368,  283,  301,  370,  635,  379,  303,
      382,  372,  363,  386,  634,  633,  383,  621,  619,  610,

      620,  372,  620,  618,    0,  711,  412,  711,  413,  620,
      615,  603,  617,  612,    0,  613,  614,  604,  606,  595,
      595,    0,    0,  600,  430,  431,  432,  433,  435,  437,
      438,  414,  614,  417,  412,  613,  612,  427,  422,  611,
      429,  424,  439,  597,  592,  598,  594,  596,  596,  589,
      593,  462,  588,    0,  588,  578,    0,    0,  580,  585,
        0,  578,  588,  585,  475,  476,  477,  478,  479,  481,
      480,  482,  594,  461,  471,  462,  472,  478,  473,  593,
      576,  612,  597,  561,  560,  560,  547,  557,  711,    0,
      551,  550,  544,  554,  545,  548,    0,  496,  518,  520,

      521,  522,  525,  523,  526,  483,  502,  431,  558,  557,
      476,  533,  711,  711,  501,  496,  427,  427,  711,  411,
      373,  387,    0,    0,  386,  529,  537,  711,  538,  540,
      542,  543,  546,  536,  389,  522,  527,  711,  711,  711,
      344,  277,  275,    0,  219,  196,  560,  711,  562,  576,
      563,  210,  180,  529,  711,  711,    0,    0,  162,  571,
      578,  136,    0,  711,  597,  599,  603,  607,  611
    } ;

static yyconst short int yy_def[370] =
    {   0,
      364,    1,  364,    3,  364,  364,  364,  364,  364,  364,
      364,  365,  364,  364,  364,  364,  364,  364,  364,  364,
      366,  364,  366,  364,  364,  364,  364,  364,  364,  366,
      364,  364,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  364,  364,  364,  364,  367,
      367,  364,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,   56,  367,   65,  367,  367,  367,
      367,  367,  367,   65,  367,  367,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,  367,
      367,  367,  367,  364,  364,  364,  364,  365,  364,  364,

      364,  366,  364,  364,  368,  366,  364,  364,  364,  364,
      364,  364,  364,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  364,
      364,  364,  364,  364,  367,  364,  367,  367,  367,  367,
      367,   56,  367,  367,  367,  367,   65,  367,  367,  369,
       65,  367,  367,  367,  367,  367,  367,  367,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  367,  367,  367,  367,  367,  365,
      368,  364,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  364,  364,  364,

      364,  364,  364,  364,   56,  364,  369,  364,  369,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  367,  367,  367,  367,  367,  367,
      367,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  364,  364,  364,  364,  364,  364,  364,
      364,  369,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  367,  367,  367,  367,  367,  367,
      367,  367,  366,  366,  366,  366,  366,  366,  366,  366,
      364,  364,  364,  364,  364,  364,  364,  364,  364,   65,
       65,   65,   65,   65,   65,   65,   65,  367,  367,  367,

      367,  367,  367,  367,  367,  366,  366,  366,  366,  366,
      366,  364,  364,  364,  364,  364,  364,  364,  364,   65,
       65,   65,   65,   65,   65,  367,  367,  364,  367,  367,
      367,  367,  367,  366,  366,  366,  366,  364,  364,  364,
      364,  364,   65,   65,   65,   65,  367,  364,  367,  367,
      367,  366,  366,  366,  364,  364,   65,   65,   65,  367,
      367,  366,   65,    0,  364,  364,  364,  364,  364
    } ;

static yyconst short int yy_nxt[765] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,    6,   21,   29,   30,   31,   32,
       21,   33,   34,   35,   36,   37,   21,   38,   21,   21,
       39,   21,   40,   41,   42,   43,   21,   44,   45,   21,
       46,   47,   48,   50,   51,   52,   51,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   50,   65,   73,
       74,   75,   76,   65,   77,   78,   79,   80,   81,   65,
       82,   65,   65,   83,   65,   84,   85,   86,   87,   65,

       88,   89,   65,   90,   91,   92,   94,   96,   94,  104,
       97,  106,  108,  109,  105,  111,  112,  103,  103,  103,
      103,  103,  103,  103,  103,  115,  103,  103,  103,  103,
      103,  117,  103,  128,  122,  119,  116,  114,  118,  120,
      123,  129,  125,  136,  121,  127,  124,  136,   96,  136,
      126,   97,  136,  137,  138,  136,  138,  137,  136,  137,
      103,  160,  137,  136,  103,  137,  131,  132,  137,  139,
      133,  140,  161,  137,  141,  136,  136,  136,  136,  134,
      136,  136,  143,  188,  136,  137,  137,  137,  137,  145,
      137,  137,  144,  142,  137,  136,  142,  146,   94,  162,

       94,  363,  165,  142,  103,  137,  163,  166,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  135,  147,
      136,  147,  136,  106,  103,  359,  202,  148,  147,  103,
      137,  203,  137,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  136,  136,  136,  136,  136,  358,  136,
      136,  103,  136,  149,  137,  137,  137,  137,  150,  137,
      137,  152,  137,  136,  153,  154,  155,  156,  157,  103,
      103,  184,  103,  137,  103,  158,  103,  103,  103,  183,

      103,  103,  103,  186,  191,  103,  185,  103,  136,  357,
      103,  356,  189,  103,  187,  194,  232,  192,  137,  193,
      196,  175,  136,  195,  190,  103,  197,  103,  234,  199,
      136,  235,  137,  238,  136,  140,  200,  201,  141,  136,
      137,  138,  136,  138,  137,  144,  136,  355,  136,  137,
      206,  136,  137,  176,  177,  141,  137,  178,  137,  136,
      137,  137,  141,  136,  136,  208,  179,  136,  136,  137,
      136,  136,  136,  137,  137,  209,  136,  137,  137,  144,
      137,  137,  137,  136,  218,  136,  137,  103,  136,  136,
      136,  136,  103,  137,  103,  137,  103,  219,  137,  137,

      137,  137,  233,  103,  236,  248,  103,  103,  240,  241,
      103,  237,  249,  103,  208,  208,  346,  345,  344,  226,
      225,  239,  243,  229,  209,  209,  227,  228,  230,  231,
      252,  242,  136,  136,  136,  136,  103,  136,  103,  136,
      136,  103,  137,  137,  137,  137,  103,  137,  103,  137,
      137,  103,  273,  103,  274,  103,  279,  343,  275,  277,
      342,  336,  341,  103,  289,  265,  268,  266,  269,  271,
      276,  272,  278,  280,  209,  270,  267,  136,  136,  136,
      136,  136,  136,  136,  136,  103,  103,  137,  137,  137,
      137,  137,  137,  137,  137,  103,  103,  103,  136,  340,

      103,  306,  103,  339,  309,  308,  337,  103,  137,  311,
      307,  300,  298,  302,  303,  301,  305,  299,  310,  304,
      136,  327,  328,  136,  136,  136,  103,  136,  136,  334,
      137,  136,  137,  137,  137,  137,  326,  137,  137,  136,
      348,  137,  136,  349,  136,  136,  103,  335,  136,  137,
      137,  103,  137,  103,  137,  137,  329,  330,  137,  331,
      103,  333,  136,  347,  136,  136,  354,  338,  362,  332,
      352,  353,  137,  136,  137,  137,  351,  350,  136,  360,
      136,  103,  103,  137,  325,  324,  323,  322,  137,  321,
      137,  320,  319,  318,  317,  316,  315,  361,   98,  314,

       98,  102,  102,  135,  135,  135,  135,  181,  181,  181,
      181,  207,  207,  207,  207,  313,  312,  103,  103,  297,
      296,  295,  294,  293,  292,  291,  290,  288,  287,  286,
      285,  284,  283,  282,  281,  103,  103,  103,  103,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  251,  250,  247,  246,  245,  244,  103,  103,  103,
      182,  224,  223,  222,  221,  220,  217,  216,  215,  214,
      213,  212,  211,  210,  151,  205,  204,  198,  103,  103,
      182,  103,  180,   97,   97,  174,  173,  172,  171,  170,
      169,  168,  167,  164,  159,  135,  151,  130,  364,  113,

      110,  107,  103,  101,  100,   99,   95,  364,   93,   49,
        5,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364
    } ;

static yyconst short int yy_chk[765] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    7,   11,    7,   22,
       11,   23,   26,   26,   22,   28,   28,   23,   33,   34,
       36,   35,   37,   38,   40,   34,   42,   44,   43,   45,
       39,   35,   41,   44,   38,   36,   34,   33,   35,   37,
       39,   45,   41,   50,   37,   43,   40,   54,   49,   53,
       42,   49,   57,   50,   51,   51,   51,   54,   55,   53,
      362,   78,   57,   59,  120,   51,   49,   49,   55,   53,
       49,   55,   78,   59,   55,   58,   60,   61,   62,   49,
       56,   63,   58,  120,   64,   58,   60,   61,   62,   62,
       56,   63,   61,   56,   64,   69,   56,   64,   94,   79,

       94,  359,   81,   56,  353,   69,   79,   81,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   65,   65,
       75,   65,   76,  106,  352,  346,  133,   65,   65,  106,
       75,  133,   76,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   66,   68,   70,   71,   72,  345,   73,
       90,  115,   91,   66,   68,   70,   71,   72,   66,   73,
       90,   68,   91,   92,   70,   70,   71,   72,   72,  114,
      116,  115,  117,   92,  119,   73,  121,  124,  125,  114,

      123,  128,  126,  117,  124,  127,  116,  185,  135,  343,
      183,  342,  121,  129,  119,  126,  183,  124,  135,  125,
      128,   91,   93,  127,  123,  186,  129,  190,  185,  132,
      137,  186,   93,  190,  139,   93,  132,  132,   93,  140,
      137,  138,  138,  138,  139,  137,  141,  341,  143,  140,
      144,  145,  138,   93,   93,  140,  141,   93,  143,  146,
      144,  145,  141,  148,  149,  150,   93,  152,  153,  146,
      154,  155,  156,  148,  149,  150,  157,  152,  153,  149,
      154,  155,  156,  158,  169,  175,  157,  193,  176,  177,
      178,  179,  184,  158,  187,  175,  192,  169,  176,  177,

      178,  179,  184,  189,  187,  202,  191,  197,  192,  193,
      194,  189,  202,  335,  207,  209,  325,  322,  321,  177,
      176,  191,  197,  178,  207,  209,  177,  177,  178,  179,
      209,  194,  225,  226,  227,  228,  235,  229,  232,  230,
      231,  234,  225,  226,  227,  228,  239,  229,  242,  230,
      231,  238,  232,  241,  234,  308,  242,  320,  235,  239,
      318,  308,  317,  243,  252,  225,  228,  226,  229,  230,
      238,  231,  241,  243,  252,  229,  227,  265,  266,  267,
      268,  269,  271,  270,  272,  274,  276,  265,  266,  267,
      268,  269,  271,  270,  272,  275,  277,  279,  298,  316,

      311,  274,  278,  315,  277,  276,  311,  306,  298,  279,
      275,  267,  265,  269,  270,  268,  272,  266,  278,  271,
      299,  299,  300,  301,  302,  304,  307,  303,  305,  306,
      299,  326,  300,  301,  302,  304,  298,  303,  305,  327,
      329,  326,  330,  330,  331,  332,  336,  307,  333,  327,
      329,  337,  330,  354,  331,  332,  301,  302,  333,  303,
      334,  305,  347,  326,  349,  351,  337,  312,  354,  304,
      334,  336,  347,  360,  349,  351,  332,  331,  350,  350,
      361,  310,  309,  360,  296,  295,  294,  293,  350,  292,
      361,  291,  288,  287,  286,  285,  284,  351,  365,  283,

      365,  366,  366,  367,  367,  367,  367,  368,  368,  368,
      368,  369,  369,  369,  369,  282,  281,  280,  273,  264,
      263,  262,  260,  259,  256,  255,  253,  251,  250,  249,
      248,  247,  246,  245,  244,  240,  237,  236,  233,  224,
      221,  220,  219,  218,  217,  216,  214,  213,  212,  211,
      210,  204,  203,  201,  200,  199,  198,  196,  195,  188,
      181,  174,  173,  172,  171,  170,  168,  166,  165,  164,
      162,  161,  160,  159,  151,  142,  134,  131,  122,  118,
      105,  102,   98,   97,   96,   89,   88,   87,   86,   85,
       84,   83,   82,   80,   77,   74,   67,   47,   30,   29,

       27,   24,   21,   20,   18,   14,    9,    5,    4,    2,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "mcplex.fl"
#define INITIAL 0
#line 2 "mcplex.fl"
/*
 * MCP parser by Joseph Traub and Jeremy Blackman
 * Copyright(C) 1996, Joseph L. Traub and Jeremy Blackman, All rights reserved
 *
 * This module is part of the NeonMuck distribution and is usable under the
 * terms and conditions of the license attendant with that software.
 *
 * MCP is a C-like language that is translated into the MUF language native
 * to the MUCK mud server.
 *
 * This code is very loosely based on the ideas and concepts of the MUV
 * grammer written by Russ Smith and Marcus Ranum.
 *
 * This file contains the code for the lexigraphical analyzer (lexer) which
 * takes the text of the input and translates it into lexemes consumed by the
 * parser.
 */

#include <sys/types.h>
#include <unistd.h>
#include <math.h>
#include <string.h>

#include "mcpstruct.h"
#include "mcpparse.h"
#include "copyright.h"

extern int yylinenum;
extern int yyerror(char *);
extern char *savestr(char *);

static char strbuf[2048];

#define com 1

#define YY_NO_UNPUT 1
#line 690 "mcplex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 46 "mcplex.fl"

#line 842 "mcplex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 365 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 711 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(com):
#line 47 "mcplex.fl"
{ yyterminate(); }
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 48 "mcplex.fl"
{ yylinenum++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "mcplex.fl"
{ }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 50 "mcplex.fl"
{ yylval.string = savestr(yytext); return COMMENT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "mcplex.fl"
{ BEGIN(com); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "mcplex.fl"
{ yylinenum++; yylval.string = savestr(yytext);
			  BEGIN(INITIAL); return COMMENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "mcplex.fl"
{ yylinenum++; yylval.string = savestr(yytext);
                          return COMMENT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "mcplex.fl"
{ yylval.string = savestr(yytext); return OBJ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "mcplex.fl"
{ yylval.string=savestr(yytext); return OBJ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "mcplex.fl"
{ yylval.val = atoi(yytext); return NUM; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "mcplex.fl"
{ return ELSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "mcplex.fl"
{ return FUNC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "mcplex.fl"
{ return IF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "mcplex.fl"
{ return DO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "mcplex.fl"
{ return FOR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "mcplex.fl"
{ return PUSH; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "mcplex.fl"
{ return RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "mcplex.fl"
{ return BREAK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "mcplex.fl"
{ return CONTINUE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "mcplex.fl"
{ return TOP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "mcplex.fl"
{ return SWITCH; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "mcplex.fl"
{ return SWITCHALL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "mcplex.fl"
{ return CASE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "mcplex.fl"
{ return DEFAULT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "mcplex.fl"
{ return WHILE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "mcplex.fl"
{ return PUBLIC; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "mcplex.fl"
{ return MAKEARRAY; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "mcplex.fl"
{ return VAR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "mcplex.fl"
{ yylval.string = savestr(yytext); return IDENT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "mcplex.fl"
{ return INCLUDE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "mcplex.fl"
{ return DEFINE; }
	YY_BREAK
case 31:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 80 "mcplex.fl"
{ return ELSEDEF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "mcplex.fl"
{ return UNDEF; }
	YY_BREAK
case 33:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 82 "mcplex.fl"
{ return ENDIF; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "mcplex.fl"
{ int i = 0, c = input();
                          strcpy(strbuf, "");
			  while(c != '\n') {
			      if(i < 2047)
				  strbuf[i++] = c;
			      c = input();
			  }
			  strbuf[i] = '\0';
			  yylval.string = savestr(strbuf);
			  return ECHODEF;
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "mcplex.fl"
{ int i = 0, c = input();
                          strcpy(strbuf, "");
			  while(c != '\n') {
			      if(i < 2047)
				  strbuf[i++] = c;
			      c = input();
			  }
			  strbuf[i] = '\0';
			  yylval.string = savestr(strbuf);
			  return IFDEF;
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "mcplex.fl"
{ int i = 0, c = input();
                          strcpy(strbuf, "");
			  while(c != '\n') {
			      if(i < 2047)
				  strbuf[i++] = c;
			      c = input();
			  }
			  strbuf[i] = '\0';
			  yylval.string = savestr(strbuf);
			  return IFNDEF;
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "mcplex.fl"
{ return BLANK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "mcplex.fl"
{ return CALL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "mcplex.fl"
{ return INCR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "mcplex.fl"
{ return DECR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "mcplex.fl"
{ return SHIFTR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "mcplex.fl"
{ return SHIFTL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "mcplex.fl"
{ return EQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "mcplex.fl"
{ return GTE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "mcplex.fl"
{ return LTE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "mcplex.fl"
{ return NE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "mcplex.fl"
{ return AND; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "mcplex.fl"
{ return OR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 128 "mcplex.fl"
{ return LT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "mcplex.fl"
{ return GT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "mcplex.fl"
{ return NOT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 131 "mcplex.fl"
{ return BITAND; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 132 "mcplex.fl"
{ return BITOR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "mcplex.fl"
{ return BITXOR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "mcplex.fl"
{ return MOD; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "mcplex.fl"
{ return DIV; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "mcplex.fl"
{ return MUL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "mcplex.fl"
{ return SUB; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "mcplex.fl"
{ return ADD; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "mcplex.fl"
{ return OPAREN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "mcplex.fl"
{ return CPAREN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 141 "mcplex.fl"
{ return SEMICOLON; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "mcplex.fl"
{ return COLON; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 143 "mcplex.fl"
{ return OBRACE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 144 "mcplex.fl"
{ return CBRACE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 145 "mcplex.fl"
{ return COMMA; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 146 "mcplex.fl"
{ return ASGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 147 "mcplex.fl"
{ return OBRACK; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "mcplex.fl"
{ return CBRACK; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "mcplex.fl"
{ int i = 1, c = input();
			  strcpy(strbuf, "\"");
			  while(i < 2047) {
			      if(c == '\\') {
				  strbuf[i++] = c;
				  strbuf[i++] = input();
			      } else if (c == '\"') {
				  strbuf[i++] = c;
				  strbuf[i] = '\0';
			          yylval.string=savestr(strbuf);
				  return STR;
			      } else if (c == '\n') {
				  yyerror("missing \"");
				  break;
			      } else strbuf[i++] = c;
			      c = input();
			  }
		          if(i == 2046)
			      yyerror("string to long");
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "mcplex.fl"
{ yyerror("Illegal input character"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 170 "mcplex.fl"
ECHO;
	YY_BREAK
#line 1351 "mcplex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 365 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 365 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 364);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 170 "mcplex.fl"
